name: MCCinema
version: '${project.version}'
main: me.snuks.mccinema.mccinema.MCCinema
api-version: 1.18
authors: [ Snuks ]
description: Browse pictures and videos in game.
commands:
  createscreen:
    description: Create a screen from a placed corner ItemFrame.
    usage: /createscreen [width] [height]

