name: MCCinema
version: '${project.version}'
main: me.snuks.mccinema.main.MCCinema
api-version: 1.18
authors: [ Snuks ]
description: Browse pictures and videos in game.
commands:
  createimage:
    description: Create a screen with an image provided by a URL.
    usage: /createimage [URL]

